swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts/{accountId}:
    get:
      tags:
        - Account Module
      summary: User Account API
      description: API for getting account's user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
      responses:
        '200':
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/accounts/{accountId}/transactions:
    get:
      tags:
        - Transaction Module
      summary: User Transactions API
      description: API for fetching account transactions
      parameters:
        - in: path
          name: accountId
          description: User's account ID
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: fromDate
          in: query
          description: Start date for fetching transactions
          required: false
          type: string
        - name: toDate
          in: query
          description: End date for fetching transactions
          required: false
          type: string
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
