swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Accounts API
      description: API for fetching the user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      responses:
        '200':
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for getting details of a specific user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
      responses:
        '200':
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions Account API
      description: API for fetching all transactions associated with a specific user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - name: fromDate
          in: query
          description: Start date for fetching transactions
          required: false
          type: string
        - name: toDate
          in: query
          description: End date for fetching transactions
          required: false
          type: string
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Details Transaction Account API
      description: API for fetching details of a specific transaction associated with a user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Details Transaction Account API
      description: API for updating details of a specific transaction associated with a user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
        - in: body
          name: body
          description: Details Transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDetailsEditables'
      responses:
        '200':
          description: Transaction details updated successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Details Transaction Account API
      description: API for deleting a specific transaction associated with a user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
        - in: path
          name: transactionId
          description: Transaction ID
          type: string
          required: true
      responses:
        '200':
          description: Transaction deleted successfully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Account'
  Account:
    type: object
    properties:
      accountId:
        type: integer
      created:
        type: string
        description: account creation date
      name:
        type: string
        description: The account name of the user
      currency:
        type: string
        description: The account currency of the user
      balance:
        type: number
        description: The current balance in the account
      ownerName:
        type: string
        description: The name of the account owner
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      transactionId:
        type: integer
      created:
        type: string
        description: transaction creation date
      description:
        type: string
        description: The description of the transaction
      currency:
        type: string
        description: The account currency of the user
      amount:
        type: integer
        description: The amount of the transaction
      balanceDate:
        type: integer
        description: The amount of the balance after the transaction is created
  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/TransactionDetails'
  TransactionDetails:
    type: object
    properties:
      type:
        type: string
        description: Transaction Type
      body:
        $ref: '#/definitions/TransactionDetailsEditables'
  TransactionDetailsEditables:
    type: object
    properties:
      category:
        type: string
        description: Transaction Category
      notes:
        type: string
        description: Transaction Notes
